openpgp: Trying to make ValidCert own a Cert.
  - I tried this before, I distinctively remember being taught this
    lesson by the compiler once before.  Unintuitively, making the
    ValidCert own the Cert constrains the lifetime of references
    returned by methods of the ValidCert.

    That is because ValidCert is a reference type, and there is a lot
    of existing code expecting to be able to drop the ValidCert and
    keep using the reference, e.g.:

      error[E0716]: temporary value dropped while borrowed
          --> openpgp/src/cert.rs:6916:19
           |
      6916 |         let sig = merged.with_policy(p, None)?.keys().subkeys()
           |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ creates a temporary value which is freed while still in use
      6917 |             .for_signing().next().unwrap().binding_signature();
           |                                                               - temporary value is freed at the end of this statement
      6918 |         assert_eq!(sig.embedded_signatures().count(), 2);
           |                    --- borrow later used here
           |
      help: consider using a `let` binding to create a longer lived value
           |
      6916 ~         let binding = merged.with_policy(p, None)?;
      6917 ~         let sig = binding.keys().subkeys()

    I fear that would mean a lot of churn, and doesn't result in nice
    looking code.